apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: test-annotations-tgdf
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: test-annotations-tgdf
    app.kubernetes.io/part-of: build-suite-test-application-ftrv
  name: test-annotations-tgdf
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: my-nginx
      app.kubernetes.io/instance: test-annotations-tgdf
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: my-nginx
        app.kubernetes.io/instance: test-annotations-tgdf
    spec:
      containers:
      - image: quay.io/tnevrlka-test/build-e2e-syzh-tenant/build-suite-test-application-ftrv/test-annotations-tgdf@sha256:63a9615b78bd2a8455b9e718e6ee7a42083b9a1dd01f1f072949d956c5065c70
        name: my-nginx
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        - containerPort: 8081
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
